### ISSUE TITLE
Glowing not working

### ISSUE THREAD

**Issue by qmained** [SkytAsul/GlowingEntities#2]
```
[20:39:47] [Server thread/WARN]: [MyPlugin] Task #85 for MyPlugin v1.0 generated an exception
java.lang.RuntimeException: java.lang.IllegalAccessException: class fr.skytasul.glowingentities.GlowingEntities$Packets cannot access a member of class net.minecraft.server.network.PlayerConnection with modifiers "private final"
        at com.qm.myplugin.pvpclasses.GlowViewManager$GlowViewer.lambda$update$3(GlowViewManager.java:72) ~[?:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at com.qm.myplugin.pvpclasses.GlowViewManager$GlowViewer.update(GlowViewManager.java:49) ~[?:?]
        at com.qm.myplugin.pvpclasses.GlowViewManager.updateView(GlowViewManager.java:102) ~[?:?]
        at com.qm.myplugin.tasks.TickTask.run(TickTask.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3714-Spigot-b31949f-3ae9069]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3714-Spigot-b31949f-3ae9069]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1259) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3714-Spigot-b31949f-3ae9069]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3714-Spigot-b31949f-3ae9069]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3714-Spigot-b31949f-3ae9069]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3714-Spigot-b31949f-3ae9069]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3714-Spigot-b31949f-3ae9069]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalAccessException: class fr.skytasul.glowingentities.GlowingEntities$Packets cannot access a member of class net.minecraft.server.network.PlayerConnection with modifiers "private final"
        at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674) ~[?:?]
        at java.lang.reflect.Field.checkAccess(Field.java:1102) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:423) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.getChannel(GlowingEntities.java:565) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.addPacketsHandler(GlowingEntities.java:681) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities.setGlowing(GlowingEntities.java:179) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities.setGlowing(GlowingEntities.java:130) ~[?:?]
        at com.qm.myplugin.pvpclasses.GlowViewManager$GlowViewer.lambda$update$3(GlowViewManager.java:69) ~[?:?]
        ... 12 more
```

**Comment by SkytAsul** [comment]
Ah shoot... that's weird I'm not having this problem. When did you build your version of Spigot?

**Comment by qmained** [comment]
> Ah shoot... that's weird I'm not having this problem. When did you build your version of Spigot?

Today, several hours ago

**Comment by SkytAsul** [comment]
Try again with 1.2.1 :)
