### ISSUE TITLE
1.3.5 does not work on paper 1.18.1

### ISSUE THREAD

**Issue by Null-K** [SkytAsul/GlowingEntities#22]
I wrote a plugin that makes item frames glow, and it runs smoothly on version 1.20.1. However, when I try to load it on Paper 1.18.1, it fails and gives the following error:
```
[15:45:57] [Server thread/INFO]: [GlowingEntities] [GlowingEntities] Found server version 1.18.1
[15:45:57] [Server thread/INFO]: [GlowingEntities] [GlowingEntities] Loaded mappings V1_18
[15:45:57] [Server thread/ERROR]: [GlowingEntities] [GlowingEntities] Glowing Entities reflection failed to initialize. The util is disabled. Please ensure your version (org.bukkit.craftbukkit.v1_18_R1) is supported.
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:?]
	at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
	at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
	at fr.skytasul.glowingentities.GlowingEntities$Packets.getField(GlowingEntities.java:702) ~[KcFrameVanisher.jar:?]
	at fr.skytasul.glowingentities.GlowingEntities$Packets.<clinit>(GlowingEntities.java:391) ~[KcFrameVanisher.jar:?]
	at fr.skytasul.glowingentities.GlowingEntities.<init>(GlowingEntities.java:51) ~[KcFrameVanisher.jar:?]
	at com.puddingkc.KcFrameVanisher.onEnable(KcFrameVanisher.java:38) ~[KcFrameVanisher.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
```

**Comment by Null-K** [comment]
I tested it again, and it runs fine on Paper 1.18.2. It seems that only 1.18.1 has an issue.

**Comment by SkytAsul** [comment]
Yeah I didn't bother adding support for a minor version. Why would you even
use 1.18.1 and not 1.18.2?

**Comment by Null-K** [comment]
> Yeah I didn't bother adding support for a minor version. Why would you even use 1.18.1 and not 1.18.2?

Thanks for the reply! I have an old server that has been stuck on version 1.18.1 for a while, but I'm planning to update it soon :D

**Comment by SkytAsul** [comment]
Alright!
